apiVersion: v1
kind: Pod
spec:
  containers:  # list of containers that you want present for your build, you can define a default container in the Jenkinsfile
    - name: docker
      image: registry.klucsik.fun/buildx
      command: ["sleep", "1d"]
      resources:
        requests:
          memory: "200Mi"
          cpu: "200m"
        limits:
          memory: "2Gi"
      volumeMounts:
        - name: docker
          mountPath: /var/run/docker.sock # We use the k8s host docker engine

    - name: kubectl
      image: registry.klucsik.fun/kubectl #TODO change this dynamically
      command: ["sleep", "1d"]
      resources:
        requests:
          memory: "200Mi"
          cpu: "100m"
        limits:
          memory: "1Gi"

  volumes:
    - name: docker
      hostPath:
        path: /var/run/docker.sock

