apiVersion: v1
kind: Namespace
metadata:
  name: oktatas-3szog


---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: oktatas-3szog-klucsikfun
  namespace: oktatas-3szog
spec:
  rules:
    - host: 3szog.8tas.klucsik.fun
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: oktatas-3szog-svc
                port:
                  number: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oktatas-3szog
  namespace: oktatas-3szog
spec:
  replicas: 1
  selector:
    matchLabels:
      type: backend
      service: oktatas-3szog
  template:
    metadata:
      labels:
        type: backend
        service: oktatas-3szog
    spec:
      containers:
        - name: backend
          image: registry.klucsik.fun/3szog_gyakorlo
          imagePullPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: oktatas-3szog-svc
  namespace: oktatas-3szog
spec:
  ports:
    - port: 80
      targetPort: 5000
  selector:
    type: backend
    service: oktatas-3szog

---
